---
title: "Three Logicians Walk Into a Bar"
output:
  html_document:
    df_print: paged
---

# Intro

### The Joke

*Three logicians walk into a bar. The bartender asks, "Do you all want a beer?"*

-   *Ada: "I don't know"*
-   *Bertrand: "I don't know"*
-   *Claude: "Yes!"*


### Explanation

How does this work? Each logician really does want a beer, but doesn't know what the others want. If the bartender's question is taken literally ("do **all** of you want a beer), no logician knows the answer - at first. (On other hand, if any of the logicians didn't want a beer, he or she could answer,"no".) After Ada and Bertrand give their "I don't know" answers (thus - they do want a beer), Claude can give a definite answer.

### Generalizations

#### Forms of the Joke

There are other forms of this joke, depending on the bartender's question.
An alternative, equally funny, but less jolly form of the joke is:

*Three logicians walk into a bar. The bartender asks, "do any of you want a beer?"*

-   *A: "I don't know"*
-   *B: "I don't know"*
-   *C: "No!"*

In this case, no one wanted a beer, but again only Claude was able to answer the bartender.

Here's a third form of the joke:

*Three logicians walk into a bar. The bartender asks, "do an odd number of you want a beer?"*

-   *A: "I don't know"*
-   *B: "I don't know"*
-   *C: "I don't know!"*

So funny!


How many jokes are there? (How many different questions can the bartender ask?)

#### Logicians' Desires

Our three logicians may or may not want a beer; 3 logicians and 2 options means there are ${2}^{3}$ = `r 2**3` ways the joke could unfold. But! Some of these outcomes are identical. For example, if it's "do you all want a beer?" and A doesn't want a beer, the answers are "no", "no", and "no", no matter what B and C want. If A wants a beer but B doesn't, the answers are "I don't know", "no", and "no", even if C wants a beer.

#### Interlude: Notation

For shorthand, let's say the "Do you wall want a beer" joke is $j_{AND}$; "Do any of you want a beer?" is $j_{OR}$, and "Do an odd number of you want a beer, $j_{XOR}$. The logicians' beer/no-beer choice is 1 for beer, 0 for no-beer, and there are three of them, so we can use a triplet of 0/1 to show what they want. We can encode the answer as "I don't know" $\mapsto$ $X$, "no" $\mapsto$ $0$, "yes" $\mapsto$ $1$. Putting it all together, the first form the joke above is
$$j_{AND}(1, 1, 1) =  \{X, X, 1\}$$

The other 7 outcomes of this form of the joke are:
$$j_{AND}(0, 0, 0) =  \{0, 0, 0\}$$
$$j_{AND}(0, 0, 1) =  \{0, 0, 0\}$$
$$j_{AND}(0, 1, 0) =  \{0, 0, 0\}$$
$$j_{AND}(0, 1, 1) =  \{0, 0, 0\}$$
$$j_{AND}(1, 0, 0) =  \{X, 0, 0\}$$
$$j_{AND}(1, 0, 1) =  \{X, 0, 0\}$$
$$j_{AND}(1, 1, 0) =  \{X, X, 0\}$$
The number of different ways $j_{AND}$ can be answered, $N_{AND}$, is 4: $\{0, 0, 0\}, \{X, 0, 0\}, \{X, X, 0\}, \{X, X, 1\}$.
